#remote_theme: beAuthentic/askclass-course-theme
theme: askclass-course-theme

title: "Kairos Communion With God"
description: >
  A ministry elective course on how to recognize God’s voice and differentiate
  it from all of the other voices that bombard our hearts and minds.
  This course will help you discern the voice of the Lord within your heart,
  clearly and consistently, leading to a deeper intimacy with Him as well as
  greater faith, hope, and joy.

acc:
  date_format: "%b %d, %y"
  short_name: "PT-603"
  color:
    theme: "#87ceeb"
    bg: "#222"
  url: "https://pt603.nissi.app"
  categories:
    - education
  logo:
    image: "logo.svg"
    size: 70
    height: 70
    alt_image: "logo.svg"
    alt_size: 200
    sizes: [ 48, 96, 144, 192, 300, 512, 800, 1024 ]
  shortcuts:
    - name: Syllabus
      url: https://pt603.nissi.app/session/syllabus
      desc: Class syllabus and contact information
  meta:
    apple_icon: "logo-square-300.png"
    og_image: "logo-square-512.png"
    shortcut:
      favicon: "favicon.ico"
      type: "image/png"
      image: "logo-96.png"
    keywords: >
      education,
      learning,
      theology,
      psychology,
      christianity
  footer:
    - icon: "school"
      href: "http://kairos.aeu.edu/"
      text: "Kairos University"
    - icon: "attribution"
      href: "https://acc.askclass.com"
      text: "AskClass Template"
  font_families:
    - Teko
    - Open+Sans
    - Josefin+Sans
    - Share+Tech+Mono
    - Lexend
    - Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200

collections_dir: content
collections:
  session:
    output: true
  segment:
    output: true

defaults:
  - scope:
      path: "*.html"
    values:
      layout: "default"
  - scope:
      type: "session"
    values:
      layout: "session"
  - scope:
      type: "segment"
    values:
      layout: "segment"

exclude:
  - CNAME
  - runme.sh
  - material
